#!/usr/bin/env bash

PLENARY="$(pwd)/spec/support/plenary/"
TREESITTER="$(pwd)/spec/support/treesitter/"

[ ! -d $PLENARY ] && git clone git@github.com:nvim-lua/plenary.nvim.git --branch=master $PLENARY
[ ! -d $TREESITTER ] && git clone git@github.com:nvim-treesitter/nvim-treesitter.git --branch=master $TREESITTER

SET_PLENARY="vim.opt.rtp:prepend('$PLENARY');"
SET_TREESITTER="vim.opt.rtp:prepend('$TREESITTER');"
SET_PLUGIN="vim.opt.rtp:prepend('.');"
CMD="require('plenary.test_harness').test_directory_command(vim.loop.cwd() .. '/spec/filetypes')"

TS_NODE_ACTION_ENV_TEST=1 nvim -u NONE --clean --headless -c "lua $SET_PLENARY $SET_TREESITTER $SET_PLUGIN $CMD"
